apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdapplication
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/argocd
    repoURL: https://github.com/a1tan/appofappssample
    targetRevision: HEAD
  syncPolicy:    
    automated:      
      allowEmpty: true
      prune: true
      selfHeal: true